### ISSUE TITLE
Not displaying

### ISSUE THREAD

**Issue by audreyong** [drom/wavedrom#140]
Not sure if I'm doing this right but I'm running windows, and I downloaded wavedrom-editor-v1.2.0-win-ia64.zip. After extracting it, I ran WaveDromEditor.exe. I see the editor and can change the text, but no diagram appears on the upper half of the screen. I'm able to export the png fine though, even though I can't see what diagram I'm making as I type it.

**Comment by drom** [comment]
What version of Windows do you use?

**Comment by audreyong** [comment]
Windows 7 Professional

**Comment by drom** [comment]
I just checked on Windows 7, and I see the rendering like this:
![capture](https://cloud.githubusercontent.com/assets/511872/13727555/abfb871e-e8ab-11e5-86e1-0e857b425e3e.PNG)

I do see abnormal behavior sometimes after start (~20% of starts).
The scroll-bar appears on the right and rendering is not happening.
![capture2](https://cloud.githubusercontent.com/assets/511872/13727574/62d0ef2e-e8ac-11e5-9e2d-1082c657b6f5.PNG)

For me it can be fixed by resizing an application window, Menu -> Rotate Layout.

Is it similar to your case? Can you attach a screenshot?

**Comment by audreyong** [comment]
The second screenshot is exactly what I'm getting. (I can attach a screen shot if you still want it, but I don't think it'll provide any additional information.) Once, when I opened WaveDrom, I got the first screenshot, but I would say that most of my experiences are of the second screenshot.
I tried Menu -> Rotate Layout, and it does fix the issue for each startup.

**Comment by drom** [comment]
Good. I am porting editor to NW.JS v0.13. Will be back after this.

**Comment by drom** [comment]
considered as fixed. reopen if any concerns.
