### ISSUE TITLE
Glitches after Spacer

### ISSUE THREAD

**Issue by wtl0** [drom/wavedrom#372]
Thank you for this perfect tool, I've been looking for such since long. However, after using sporadically (online editor), I've found an issue.

Issue: After a spacer, there might show up a glitch in the rendering. Please compare picture below, red cycle.
![grafik](https://user-images.githubusercontent.com/108241008/190984966-72ca6883-48de-48af-ada9-31d2a4bd702f.png)

The same glitch occurs, when the spacer is moved to an earlier position.
`  {name: 'ack', wave: '1...|..10.'},`
![grafik](https://user-images.githubusercontent.com/108241008/190986565-fd4f6b6f-c240-4835-868b-5a1b25f87482.png)

**Comment by wtl0** [comment]
Maybe this is a feature instead of a bug, the same occurs without spacers:
`{ "signal" : [
{ "name": "fine", "wave": "1..0.." },
{ "name": "documentation gap?",  "wave": "1.100." },
]}`
![grafik](https://user-images.githubusercontent.com/108241008/190992129-9bcd6648-065d-4d48-b3e5-962a37971fa8.png)
Obviously  `"00"` is not the same as `"0."`
?

**Comment by DmitTrix** [comment]
I would treat this as a feature rather than a bug.  It's useful to represent glitches (as a [real electrical issue](https://en.wikipedia.org/wiki/Glitch#Electronics_glitch), not just a rendering problem) when needed.

Proper visual rendering can be achieved in all cases by using the `.` ("repeat previous value") command instead of `0` or `1`.

Formally documenting this would be good, though.

**Comment by drom** [comment]
Documentation PR is welcome
