### ISSUE TITLE
Tick and Tock Broken

### ISSUE THREAD

**Issue by DrMatthewJApplegate** [drom/wavedrom#378]
https://wavedrom.com/editor.html

Tick and tock no longer work. Here's a testcase.

{signal: [
    {name: 'clock', wave: 'P...........'},
  ],
  head:{
   text:'WaveDrom example',
   tock:1,
   every:1
 }
}

**Comment by Timmmm** [comment]
They works in `foot` but not in `head`.

**Comment by gmoreto** [comment]
'tick' still works but it seems 'every' doesn't. comment it out and ticks appear again

**Comment by Ganesh-AT** [comment]
Problem crept in due to the update from var to let for render-marks.js

Line 34 declares _offset_ as const in local scope of the code segment that handles tick / tock value being a single number, but _offset_ is a 'let' variable that is supposed to be available everywhere in the function.

Line 34 of https://github.com/wavedrom/wavedrom/blob/trunk/lib/render-marks.js

cc @drom 

Just removing the 'const ' from the line fixed the problem.

![image](https://user-images.githubusercontent.com/6980722/235291663-ad7f31c1-6b37-4432-898f-303ef6197503.png)
